package b4a.SapyLiveSystem.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_grvstockdetaillinepage{

public static void LS_general(anywheresoftware.b4a.BA ba, android.view.View parent, anywheresoftware.b4a.keywords.LayoutValues lv, java.util.Map props,
java.util.Map<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) throws Exception {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("label9").vw.setTop((int)((0d / 100 * height)));
views.get("label9").vw.setHeight((int)((7d / 100 * height) - ((0d / 100 * height))));
views.get("label9").vw.setLeft((int)((0d / 100 * width)));
views.get("label9").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("lblsageno").vw.setTop((int)((0d / 100 * height)));
views.get("lblsageno").vw.setHeight((int)((7d / 100 * height) - ((0d / 100 * height))));
views.get("lblsageno").vw.setLeft((int)((25d / 100 * width)));
views.get("lblsageno").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("label3").vw.setTop((int)((7d / 100 * height)));
views.get("label3").vw.setHeight((int)((14d / 100 * height) - ((7d / 100 * height))));
views.get("label3").vw.setLeft((int)((0d / 100 * width)));
views.get("label3").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("lblcode").vw.setTop((int)((7d / 100 * height)));
views.get("lblcode").vw.setHeight((int)((14d / 100 * height) - ((7d / 100 * height))));
views.get("lblcode").vw.setLeft((int)((25d / 100 * width)));
views.get("lblcode").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("lbldesc").vw.setTop((int)((14d / 100 * height)));
views.get("lbldesc").vw.setHeight((int)((21d / 100 * height) - ((14d / 100 * height))));
views.get("lbldesc").vw.setLeft((int)((25d / 100 * width)));
views.get("lbldesc").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("label5").vw.setTop((int)((14d / 100 * height)));
views.get("label5").vw.setHeight((int)((21d / 100 * height) - ((14d / 100 * height))));
views.get("label5").vw.setLeft((int)((0d / 100 * height)));
views.get("label5").vw.setWidth((int)((20d / 100 * height) - ((0d / 100 * height))));
views.get("label6").vw.setTop((int)((21d / 100 * height)));
views.get("label6").vw.setHeight((int)((28d / 100 * height) - ((21d / 100 * height))));
views.get("label6").vw.setLeft((int)((0d / 100 * width)));
views.get("label6").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("lblqty").vw.setTop((int)((21d / 100 * height)));
views.get("lblqty").vw.setHeight((int)((28d / 100 * height) - ((21d / 100 * height))));
views.get("lblqty").vw.setLeft((int)((25d / 100 * width)));
views.get("lblqty").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("label1").vw.setTop((int)((28d / 100 * height)));
views.get("label1").vw.setHeight((int)((35d / 100 * height) - ((28d / 100 * height))));
views.get("label1").vw.setLeft((int)((0d / 100 * width)));
views.get("label1").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("txtqtytoprocess").vw.setTop((int)((28d / 100 * height)));
views.get("txtqtytoprocess").vw.setHeight((int)((35d / 100 * height) - ((28d / 100 * height))));
views.get("txtqtytoprocess").vw.setLeft((int)((25d / 100 * width)));
views.get("txtqtytoprocess").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("label2").vw.setTop((int)((35d / 100 * height)));
views.get("label2").vw.setHeight((int)((42d / 100 * height) - ((35d / 100 * height))));
views.get("label2").vw.setLeft((int)((0d / 100 * width)));
views.get("label2").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("label4").vw.setTop((int)((42d / 100 * height)));
views.get("label4").vw.setHeight((int)((49d / 100 * height) - ((42d / 100 * height))));
views.get("label4").vw.setLeft((int)((0d / 100 * width)));
views.get("label4").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("label7").vw.setTop((int)((49d / 100 * height)));
views.get("label7").vw.setHeight((int)((56d / 100 * height) - ((49d / 100 * height))));
views.get("label7").vw.setLeft((int)((0d / 100 * height)));
views.get("label7").vw.setWidth((int)((20d / 100 * height) - ((0d / 100 * height))));
views.get("label8").vw.setTop((int)((56d / 100 * height)));
views.get("label8").vw.setHeight((int)((63d / 100 * height) - ((56d / 100 * height))));
views.get("label8").vw.setLeft((int)((0d / 100 * width)));
views.get("label8").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("label10").vw.setTop((int)((73d / 100 * height)));
views.get("label10").vw.setHeight((int)((80d / 100 * height) - ((73d / 100 * height))));
views.get("label10").vw.setLeft((int)((0d / 100 * width)));
views.get("label10").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("label11").vw.setTop((int)((80d / 100 * height)));
views.get("label11").vw.setHeight((int)((87d / 100 * height) - ((80d / 100 * height))));
views.get("label11").vw.setLeft((int)((0d / 100 * width)));
views.get("label11").vw.setWidth((int)((25d / 100 * width) - ((0d / 100 * width))));
views.get("lbldateexpirydate").vw.setTop((int)((80d / 100 * height)));
views.get("lbldateexpirydate").vw.setHeight((int)((87d / 100 * height) - ((80d / 100 * height))));
views.get("lbldateexpirydate").vw.setLeft((int)((25d / 100 * width)));
views.get("lbldateexpirydate").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("txtsupplierbatchno").vw.setTop((int)((73d / 100 * height)));
views.get("txtsupplierbatchno").vw.setHeight((int)((80d / 100 * height) - ((73d / 100 * height))));
views.get("txtsupplierbatchno").vw.setLeft((int)((25d / 100 * width)));
views.get("txtsupplierbatchno").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("txtamountoflabelstoprint").vw.setTop((int)((35d / 100 * height)));
views.get("txtamountoflabelstoprint").vw.setHeight((int)((42d / 100 * height) - ((35d / 100 * height))));
views.get("txtamountoflabelstoprint").vw.setLeft((int)((25d / 100 * width)));
views.get("txtamountoflabelstoprint").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("txtqtydamages").vw.setTop((int)((42d / 100 * height)));
views.get("txtqtydamages").vw.setHeight((int)((49d / 100 * height) - ((42d / 100 * height))));
views.get("txtqtydamages").vw.setLeft((int)((25d / 100 * width)));
views.get("txtqtydamages").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("lbllinenotes").vw.setTop((int)((49d / 100 * height)));
views.get("lbllinenotes").vw.setHeight((int)((56d / 100 * height) - ((49d / 100 * height))));
views.get("lbllinenotes").vw.setLeft((int)((25d / 100 * width)));
views.get("lbllinenotes").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("txtrecnotes").vw.setTop((int)((56d / 100 * height)));
views.get("txtrecnotes").vw.setHeight((int)((73d / 100 * height) - ((56d / 100 * height))));
views.get("txtrecnotes").vw.setLeft((int)((25d / 100 * width)));
views.get("txtrecnotes").vw.setWidth((int)((100d / 100 * width) - ((25d / 100 * width))));
views.get("btnpicture").vw.setTop((int)((90d / 100 * height)));
views.get("btnpicture").vw.setHeight((int)((100d / 100 * height) - ((90d / 100 * height))));
views.get("btnpicture").vw.setLeft((int)((0d / 100 * width)));
views.get("btnpicture").vw.setWidth((int)((33d / 100 * width) - ((0d / 100 * width))));
views.get("btnsignature").vw.setTop((int)((90d / 100 * height)));
views.get("btnsignature").vw.setHeight((int)((100d / 100 * height) - ((90d / 100 * height))));
views.get("btnsignature").vw.setLeft((int)((33d / 100 * width)));
views.get("btnsignature").vw.setWidth((int)((66d / 100 * width) - ((33d / 100 * width))));
views.get("btnreturn").vw.setTop((int)((90d / 100 * height)));
views.get("btnreturn").vw.setHeight((int)((100d / 100 * height) - ((90d / 100 * height))));
views.get("btnreturn").vw.setLeft((int)((66d / 100 * width)));
views.get("btnreturn").vw.setWidth((int)((100d / 100 * width) - ((66d / 100 * width))));

}
}